### ISSUE TITLE
example 不能运行

### ISSUE THREAD

**Issue by killangell** [Micro-sheep/efinance#118]
```
import efinance as ef
# 股票代码
stock_code = '600519'
ef.stock.get_quote_history(stock_code)

```

错误信息：

> Traceback (most recent call last):
>   File "C:/Work/gitee/biga_shares/test_code/efinance.py", line 1, in <module>
>     import efinance as ef
>   File "C:\Work\gitee\biga_shares\test_code\efinance.py", line 4, in <module>
>     ef.stock.get_quote_history(stock_code)
> AttributeError: partially initialized module 'efinance' has no attribute 'stock' (most likely due to a circular import)

**Comment by killangell** [comment]
抱歉是我的本地文件名和库重名了
