### ISSUE TITLE
股票代码存在，有异常状态，处理时跳出exception，附log

### ISSUE THREAD

**Issue by six7ths** [Micro-sheep/efinance#12]
我用了全部股票代码试了一下昨天的数据获取， 总体成功了，除了如下4个代码。 我单独抽取了这些异常log的股票代码。 请帮助看看，是什么原因？是否代码异常处理里面处理一下这个类型的异常

601206
603302
688688
300646

 0%|          | 0/4 [00:00<?, ?it/s]Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 201, in start
    _df = get_quote_history_single(
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 34, in run
    values = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 154, in get_quote_history_single
    quote_id = get_quote_id(stock_code)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 87, in get_quote_id
    raise Exception(f'证券代码 {stock_code} 可能有误')
Exception: 证券代码 300646 可能有误
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 201, in start
    _df = get_quote_history_single(
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 34, in run
    values = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 154, in get_quote_history_single
    quote_id = get_quote_id(stock_code)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 87, in get_quote_id
    raise Exception(f'证券代码 {stock_code} 可能有误')
Exception: 证券代码 603302 可能有误
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 201, in start
    _df = get_quote_history_single(
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 34, in run
    values = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 154, in get_quote_history_single
    quote_id = get_quote_id(stock_code)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 87, in get_quote_id
    raise Exception(f'证券代码 {stock_code} 可能有误')
Exception: 证券代码 601206 可能有误
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 201, in start
    _df = get_quote_history_single(
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 34, in run
    values = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\stock\getter.py", line 154, in get_quote_history_single
    quote_id = get_quote_id(stock_code)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\efinance\utils\__init__.py", line 87, in get_quote_id
    raise Exception(f'证券代码 {stock_code} 可能有误')
Exception: 证券代码 688688 可能有误
  0%|          | 0/4 [00:08<?, ?it/s]

**Comment by Micro-sheep** [comment]
我逐个看了一下，这是因为这些股票因为种种原因未能上市。以 `688688`(蚂蚁集团)为例，它因为一些原因被暂停上市了，所以不会有股票行情数据。
![image](https://user-images.githubusercontent.com/56242295/129431312-f6b48ff3-280a-4d7d-bf97-6bcf3879d9cf.png)

**Comment by six7ths** [comment]
明白了。 去之前，我把这几个代码去除掉，就一切正常了
