### ISSUE TITLE
各位大佬，python FastAPI 请求调用会报 ValueError: signal only works in main thread 如何解决？

### ISSUE THREAD

**Issue by h3clikejava** [Micro-sheep/efinance#129]
新手小白第一次写python 用的 fastAPI

启动服务器： uvicorn source.server:app --host 0.0.0.0 --reload

fastAPI：
@app.get("/stock")
def stock():
    import efinance as ef
    aaa = ef.stock.get_quote_history('600519')
    print('aaa', aaa)

直接报错了，说是必须在主线程执行。
如果直接用终端python xxx.py 执行就可以。
请问如何在fastAPI里直接调用呢？感谢大佬们🙏

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/anaconda3/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/anaconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/anaconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./source/server.py", line 110, in chat
    import efinance as ef
  File "/opt/anaconda3/lib/python3.8/site-packages/efinance/__init__.py", line 5, in <module>
    from efinance.api import (stock,
  File "/opt/anaconda3/lib/python3.8/site-packages/efinance/api/__init__.py", line 1, in <module>
    import efinance.stock as stock
  File "/opt/anaconda3/lib/python3.8/site-packages/efinance/stock/__init__.py", line 1, in <module>
    from .getter import (get_all_company_performance, get_all_report_dates,
  File "/opt/anaconda3/lib/python3.8/site-packages/efinance/stock/getter.py", line 31, in <module>
    signal.signal(signal.SIGINT, multitasking.killall)
  File "/opt/anaconda3/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

**Comment by Micro-sheep** [comment]
> 新手小白第一次写python 用的 fastAPI
> 
> 
> 
> 启动服务器： uvicorn source.server:app --host 0.0.0.0 --reload
> 
> 
> 
> fastAPI：
> 
> @app.get("/stock")
> 
> def stock():
> 
>     import efinance as ef
> 
>     aaa = ef.stock.get_quote_history('600519')
> 
>     print('aaa', aaa)
> 
> 
> 
> 直接报错了，说是必须在主线程执行。
> 
> 如果直接用终端python xxx.py 执行就可以。
> 
> 请问如何在fastAPI里直接调用呢？感谢大佬们🙏
> 
> 
> 
> ERROR:    Exception in ASGI application
> 
> Traceback (most recent call last):
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
> 
>     result = await app(  # type: ignore[func-returns-value]
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
> 
>     return await self.app(scope, receive, send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
> 
>     await super().__call__(scope, receive, send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
> 
>     await self.middleware_stack(scope, receive, send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
> 
>     raise exc
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
> 
>     await self.app(scope, receive, _send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
> 
>     raise exc
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
> 
>     await self.app(scope, receive, sender)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
> 
>     raise e
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
> 
>     await self.app(scope, receive, send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
> 
>     await route.handle(scope, receive, send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
> 
>     await self.app(scope, receive, send)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
> 
>     response = await func(request)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 231, in app
> 
>     raw_response = await run_endpoint_function(
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
> 
>     return await run_in_threadpool(dependant.call, **values)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
> 
>     return await anyio.to_thread.run_sync(func, *args)
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
> 
>     return await get_asynclib().run_sync_in_worker_thread(
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
> 
>     return await future
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
> 
>     result = context.run(func, *args)
> 
>   File "./source/server.py", line 110, in chat
> 
>     import efinance as ef
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/efinance/__init__.py", line 5, in <module>
> 
>     from efinance.api import (stock,
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/efinance/api/__init__.py", line 1, in <module>
> 
>     import efinance.stock as stock
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/efinance/stock/__init__.py", line 1, in <module>
> 
>     from .getter import (get_all_company_performance, get_all_report_dates,
> 
>   File "/opt/anaconda3/lib/python3.8/site-packages/efinance/stock/getter.py", line 31, in <module>
> 
>     signal.signal(signal.SIGINT, multitasking.killall)
> 
>   File "/opt/anaconda3/lib/python3.8/signal.py", line 47, in signal
> 
>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
> 
> ValueError: signal only works in main thread
> 
> 

试试把 import 操作写在文件顶部，而不是写在路由函数里面。

**Comment by h3clikejava** [comment]
我用的streamlit，在它的线程里就一直有问题，把import写在顶部也有问题。不过我现在不用streamlit了，改为node前端了，所以算规避了这个问题，先关了。
