### ISSUE TITLE
efinance.stock.get_latest_quote() 的bug

### ISSUE THREAD

**Issue by opiiopo** [Micro-sheep/efinance#28]
当传入的列表长度好像大于600多就会报错。
Traceback (most recent call last):
  File "G:\StockSpider\main.py", line 100, in <module>
    stockData = pandas.DataFrame(efinance.stock.get_latest_quote(stocks))
  File "C:\Python39\lib\site-packages\efinance\utils\__init__.py", line 36, in run
    values = func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\efinance\stock\getter.py", line 515, in get_latest_quote
    json_response = session.get(url,
  File "C:\Users\opiiopo\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Micro-sheep** [comment]
你的发现是对的，我在文档中声明如下

![image](https://user-images.githubusercontent.com/56242295/146770411-44136f98-28e7-42ed-9b6a-ae6866c59595.png)

对于获取很多只股票的实时行情，建议是使用`  efinance.stock.get_realtime_quptes`，文档如下 
[获取市场实时行情](https://efinance.readthedocs.io/en/latest/api/?highlight=get_realtime_q#efinance.stock.get_realtime_quotes)

**Comment by opiiopo** [comment]
我把股票列表分成多个500长度的列表再合并也能用，懒得改之前的代码了(:

**Comment by Micro-sheep** [comment]
> 我把股票列表分成多个500长度的列表再合并也能用，懒得改之前的代码了(:

哈哈，聪明。
