### ISSUE TITLE
ef.stock.get_base_info（）获取多只股票信息报错。

### ISSUE THREAD

**Issue by scfoxc** [Micro-sheep/efinance#67]
```
stock_code = ['000001','159949'] 
df = ef.stock.get_base_info(stock_code) print(df)
```

运行后报错如下：
```
Processing => 159949: 100%|██████████| 2/2 [00:00<00:00, 14.22it/s]Traceback (most recent call last):
  File "C:\Users\hdadmin\PycharmProjects\study\data\stock.py", line 58, in <module>
    df = ef.stock.get_base_info(stock_code)
  File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\utils\__init__.py", line 37, in run
    values = func(*args, **kwargs)
  File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\stock\getter.py", line 142, in get_base_info
    return get_base_info_muliti(stock_codes)
  File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\stock\getter.py", line 88, in get_base_info_muliti
    df = df.dropna(subset=['股票代码'])
  File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 6002, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['股票代码']
Processing => 159949: 100%|██████████| 2/2 [00:00<00:00, 11.64it/s]

```
Mac和win环境都测试，报错一样，获取单个股票信息没问题。

**Comment by Micro-sheep** [comment]
> ```
> stock_code = ['000001','159949'] 
> df = ef.stock.get_base_info(stock_code) print(df)
> ```
> 
> 运行后报错如下：
> 
> ```
> Processing => 159949: 100%|██████████| 2/2 [00:00<00:00, 14.22it/s]Traceback (most recent call last):
>   File "C:\Users\hdadmin\PycharmProjects\study\data\stock.py", line 58, in <module>
>     df = ef.stock.get_base_info(stock_code)
>   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\utils\__init__.py", line 37, in run
>     values = func(*args, **kwargs)
>   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\stock\getter.py", line 142, in get_base_info
>     return get_base_info_muliti(stock_codes)
>   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\stock\getter.py", line 88, in get_base_info_muliti
>     df = df.dropna(subset=['股票代码'])
>   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 6002, in dropna
>     raise KeyError(np.array(subset)[check].tolist())
> KeyError: ['股票代码']
> Processing => 159949: 100%|██████████| 2/2 [00:00<00:00, 11.64it/s]
> ```
> 
> Mac和win环境都测试，报错一样，获取单个股票信息没问题。

已修复，更新到 `v0.4.8` 即可。

**Comment by scfoxc** [comment]
> > ```
> > stock_code = ['000001','159949'] > 
> > df = ef.stock.get_base_info(stock_code) > print(df)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 运行后报错如下：
> > ```
> > Processing => 159949: 100%|██████████| 2/2 [00:00<00:00, 14.22it/s]Traceback (most recent call last):
> >   File "C:\Users\hdadmin\PycharmProjects\study\data\stock.py", line 58, in <module>
> >     df = ef.stock.get_base_info(stock_code)
> >   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\utils\__init__.py", line 37, in run
> >     values = func(*args, **kwargs)
> >   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\stock\getter.py", line 142, in get_base_info
> >     return get_base_info_muliti(stock_codes)
> >   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\efinance\stock\getter.py", line 88, in get_base_info_muliti
> >     df = df.dropna(subset=['股票代码'])
> >   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
> >     return func(*args, **kwargs)
> >   File "C:\Users\hdadmin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 6002, in dropna
> >     raise KeyError(np.array(subset)[check].tolist())
> > KeyError: ['股票代码']
> > Processing => 159949: 100%|██████████| 2/2 [00:00<00:00, 11.64it/s]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Mac和win环境都测试，报错一样，获取单个股票信息没问题。
> 
> 已修复，更新到 `v0.4.8` 即可。

已解决，非常感谢。
